export const PARENT_DIV_DURATION_TIME = 1;

export const Y_AXIS_INITIAL_POSITION = -20;
export const X_AXIS_INITIAL_POSITION = 50;

export const PRIMARY_HEADING_DELAY_TIME = 0.5;
export const PRIMARY_HEADING_DURATION_TIME = 0.5;

export const SECONDARY_HEADING_DELAY_TIME = 0.3;
export const SECONDARY_HEADING_DURATION_TIME = 0.5;

export const DESCRIPTION_DELAY_TIME = 0.7;
export const DESCRIPTION_DURATION_TIME = 0.5;

export const CONTENT_DIV_DELAY_TIME = 0.9;
export const CONTENT_DIV_DURATION_TIME = 0.6;

export const CONTENT_DIV_DELAY_TIME_EXTENDED = 1.1;

export const HOVER_SCALE = 1.05;
